// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
  /// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDZdcB095c2lR2xBda_O6QfbYs923WG4',
    appId: '1:255413402478:web:3ed84973167d2d81b75f7f',
    messagingSenderId: '255413402478',
    projectId: 'popp-71efb',
    authDomain: 'popp-71efb.firebaseapp.com',
    storageBucket: 'popp-71efb.firebasestorage.app',
    measurementId: 'G-T24PZPK0XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoogLT6QUfVICvPJe0Rj1ttccLXz-Rm70',
    appId: '1:255413402478:android:2d7f4278e963ba22b75f7f',
    messagingSenderId: '255413402478',
    projectId: 'popp-71efb',
    storageBucket: 'popp-71efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-S_RtYjVSS2zMwFlfS_jodKixQhJSlc',
    appId: '1:255413402478:android:76753981aa161607b75f7f',
    messagingSenderId: '255413402478',
    projectId: 'popp-71efb',
    storageBucket: 'popp-71efb.firebasestorage.app',
    iosBundleId: 'com.popp.abike',
  );
}
