// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDZdcB095c2lR2xBda_O6QfbYs923WG4',
    appId: '1:255413402478:web:3d92f5516384e90bb75f7f',
    messagingSenderId: '255413402478',
    projectId: 'popp-71efb',
    authDomain: 'popp-71efb.firebaseapp.com',
    storageBucket: 'popp-71efb.firebasestorage.app',
    measurementId: 'G-V4FNP42WJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoogLT6QUfVICvPJe0Rj1ttccLXz-Rm70',
    appId: '1:255413402478:android:76753981aa161607b75f7f',
    messagingSenderId: '255413402478',
    projectId: 'popp-71efb',
    storageBucket: 'popp-71efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-S_RtYjVSS2zMwFlfS_jodKixQhJSlc',
    appId: '1:255413402478:ios:ba66bf2d2572fab9b75f7f',
    messagingSenderId: '255413402478',
    projectId: 'popp-71efb',
    storageBucket: 'popp-71efb.firebasestorage.app',
    androidClientId: '255413402478-045msv2n4vnkjtacsml9vg9ieu33kt5m.apps.googleusercontent.com',
    iosClientId: '255413402478-41d2jo678e3c8e1v9oec83ue5a7pphla.apps.googleusercontent.com',
    iosBundleId: 'com.popp.abike',
  );
}
