const List<String> bikeBrands = [
  'Royal Enfield',
  'KTM',
  'Bajaj',
  'TVS',
  'Yamaha',
  'Suzuki',
  'Honda',
  'Hero MotoCorp',
  'Kawasaki',
  'Triumph',
  'Harley-Davidson',
  'BMW Motorrad',
  'Ducati',
  'Benelli',
  'CFMoto',
  'Husqvarna',
  'Jawa',
  'Yezdi',
  'Aprilia',
  'Moto Guzzi',
  'MV Agusta',
  'Zontes',
  'Keeway'
];

const List<String> countryCodes = ["+91", "+1"];

const List<String> yesNoNA = ["Yes", "No"];

const List<String> stateNames = [
  'Andhra Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Chandigarh',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Puducherry'
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Arunachal Pradesh',
  'Uttarakhand',
  'West Bengal',
];
